[package]
name = "sqlx-mssql-test"
version = "0.1.0"
authors = ["Max Nachlinger"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
sqlx = { version = "0.4.0-beta.1", default-features = false, features = [ "runtime-tokio", "macros", "mssql" ] }
